version: "3.9"
networks:
  redis-internal:
    name: redis-internal
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: redis-python
    networks:
      - redis-internal
    hostname: redis-python

    restart: unless-stopped

    ports:
      - 6379:6379